### PR TITLE
New Code Base

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
You might be interested in this new code base and functionality.

### CODE REVIEW

**Comment by Bengt** [comment]
Awesome that one can install the package via pip now. Thanks for the PR!

**Comment by BebeSparkelSparkel** [comment]
NP! What are you using the package for?

**Comment by Bengt** [comment]
Most recently I use this module to print the fitness in a genetic algorithm. These get small quickly, so using the scientific notation I can avoid counting zeros and the configurable precision makes the numbers more easily readable.

**Comment by BebeSparkelSparkel** [comment]
I've been applying a pseudo genetic algorithm to an optimization problem that tries to reduce the material consumed in manufacturing processes. Recently, I have been looking for ways to improve. What is the base package you are using for your implementation?

**Comment by Bengt** [comment]
I usually use my own implementations instead of a library, because that makes comparing them easier. Here is an EA and some methods I implemented as preparation for an university exam a few years back: 

https://github.com/Bengt/Computational-Intelligence/tree/master/ea

**Pull request merged**
